CREATE TABLE ENTITY_STATUS(  
    code VARCHAR(15) NOT NULL PRIMARY KEY,
    description VARCHAR(200)
);

CREATE TABLE COUNTRY(  
    name VARCHAR(50) NOT NULL PRIMARY KEY 
);

CREATE TABLE LOCALITY(  
    id int NOT NULL PRIMARY KEY,
    country VARCHAR(50) NOT NULL,
    postalCode VARCHAR(10) NOT NULL,
    name VARCHAR(60) NOT NULL,
    FOREIGN KEY (country) REFERENCES COUNTRY (name)
);

CREATE TABLE ADRESS(  
    id INT NOT NULL PRIMARY KEY,
    idLocality INT NOT NULL,
    street VARCHAR(100) NOT NULL,
    number INT NOT NULL,
    FOREIGN KEY (idLocality) REFERENCES LOCALITY (id)
);
